set PYTHONPATH=%PYTHONPATH%;%USD_INSTALL_ROOT%\lib\python;%USD_PLUGIN_ROOT%\lib\python
set PATH=%PATH%;%USD_INSTALL_ROOT%\lib;%USD_INSTALL_ROOT%\bin;%USD_PLUGIN_ROOT%\bin
set PXR_PLUGINPATH_NAME=%USD_PLUGIN_ROOT%\plugin

%USD_INSTALL_ROOT%\bin\usdview.cmd %*
